image: docker:latest
services:
- docker:dind

stages:
- build

maven-build:
  image: maven:3-jdk-8
  stage: build
  script: "mvn package -B -DskipTests=true"
  artifacts:
    paths:
    - target/*.jar